### ISSUE TITLE
STA9750 Will-Peters MiniProject #00

### ISSUE THREAD

**Issue by Will-Peters** [Will-Peters/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://Will-Peters.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @Will-Peters !

Peer Feedback:

- @Malexandra-Jerez
- @whaleron
- @Haina0

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @Will-Peters.

Website URL should be: https://Will-Peters.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @Will-Peters and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by whaleron** [comment]
@Will-Peters nice start!
I can help you fix your link. 
You have a space in your markdown: [Linkedin] (your URL), it should be [Linkedin](your URL)

**Comment by Malexandra-Jerez** [comment]
Hi @Will-Peters <https://github.com/Will-Peters>!

Great use of text. You are getting it. The link I was unsure how to fix,
but perhaps working on displaying link correctly is my suggestion [I'll be
looking into it too].

Kindly,
Maria Alexandra Jerez

**Comment by Haina0** [comment]
Hi @Will-Peters  great job getting your website running, after reading the previous comments looks like you were able to fix the issue with the link. Would you mind sharing how you did so, as I'm having a similar issue with mine?

**Comment by Will-Peters** [comment]
> @Will-Peters nice start! I can help you fix your link. You have a space in your markdown: [Linkedin] (your URL), it should be [Linkedin](your URL)

That was exactly the solution I also had to republish the R website file, as the index didn't seem to work by itself

**Comment by Will-Peters** [comment]
> Hi @Will-Peters great job getting your website running, after reading the previous comments looks like you were able to fix the issue with the link. Would you mind sharing how you did so, as I'm having a similar issue with mine?

@Haina0 I am not sure if your website is not working to go to the GIThub website or if you inbuilt in a hyperlink, but have you pushed/committed the other files?
