### ISSUE TITLE
STA9750 Will-Peters MiniProject #01

### ISSUE THREAD

**Issue by Will-Peters** [Will-Peters/STA9750-2024-FALL#2]

**Comment by Will-Peters** [comment]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #01 - check it out!

https://will-peters.github.io/STA9750-2024-FALL/mp01.html

**Comment by michaelweylandt** [comment]
Thanks @Will-Peters !

Peer Feedback:

- @jasonamey
- @ElissaLeung
- @matata668
- @Malexandra-Jerez

It is now time for the peer feedback round for Mini-Project #01. Please
review @Will-Peters's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric,
please grade their submission out of a total of 50 points.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @Will-Peters, but you are of course
welcome to initiate a discussion.

@Will-Peters: please engage fully with your peers. They are here to help you!

Submission URL should be: https://Will-Peters.github.io/STA9750-2024-FALL/mp01.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by matata668** [comment]
Hi @Will-Peters , 

Congratulation on your first mini project. 

Here is my breakdown for grading:

Written Communication: 5
The answers are all set up giving us the data for better idea. But, It would be great if we could know what those data meant. You could maybe add the question or just a sentence explaining what those data mean. A couple times, the flow of the project was a bit off. I

Project Skeleton: 10

Formatting & Display: 7

Code Quality: 7
There were virtually no comments throughout the code about which block did what. 

Data Preparation: 10
N/A

Overall: 39

**Comment by ElissaLeung** [comment]
Hi @Will-Peters!

See my feedback below:

**Written Communication:** 6/10
There were a few sentences explaining some of your code, however, most of the report was just a list of metrics without explanation. Maybe you could include a few sentences between each task to explain these metrics in more detail. Also an introduction, conclusion and transition paragraphs would help readers better understand the flow of the project.

**Project Skeleton:** 10/10
All the tasks were completed.

**Formatting & Display:** 4/10
More use of the markdown tools would be helpful to create a more visual project report. Since no code chunks were used, there weren't any tables outputted/displayed. With code chunks in the Quarto markdown file, you can display code output and fancy tables.

**Code Quality:** 7/10
The code can run, but since there are no code chunks in the Quarto markdown file, the audience cannot see the code output. Additionally, it is difficult to interpret the code since everything is bunched together and there are limited comments. I’d recommend reformatting the file to include code chunks and some transition sentences and/or description sentences for code chunks so the audience can more easily understand.

**Data Preparation:** 10/10

**Total:** 37/50

Elissa

**Comment by charles-ramirez** [comment]
Hi, @jasonamey,

This is just a reminder that your peer review is due today at 11:45 pm.

**Comment by jasonamey** [comment]
Hi @Will-Peters 

I think it's an arguably solid strategy to  outline your answers at the onset of your document to highlight the document's conclusions without being surrounded by code.  That said, there could be some additional context or scaffolding around your answers (maybe at least re-state the question?). 

There is some inconsistency in your formatting of your answers. Some numbers include commas. Some do not. I would pick a style (I prefer commas) and stick to that. 

Were you trying to escape a line-break here?  I'm pretty sure Quarto / mark-down handles line breaks depending on how you elect to mark up your text : 
![Screenshot 2024-10-02 at 8 01 02 PM](https://github.com/user-attachments/assets/fb32e345-060f-4008-8bc9-7490d98bdcaf)
^next time you'll probably want to do a double-check to see if anything like this sticks out. 

I have to be honest, your document is difficult to read. It's really hard to read code in a serif-font, formatted like written English language. I'd also use double-spacing judiciously in your code, like when you are logically separating distinct components. 

Have you had a chance to try using code blocks with backticks? 
https://quarto.org/docs/output-formats/html-code.html

(do you know the backtick key? it's the same as the tilde, often at the top left corner of your keyboard)

Next time, I would experiment with this markdown strategy. It'll make the document much easier for the reader to parse and understand.  

Me? I simply can't read code in a serif-font. It's just really difficult on the human eye to work through. Working out a way to properly format your code snippets should probably be a top priority for your next submission. 

You'll also need to work out a little more narrative support for your project next time. Again, it's an understandable decision to separate out your answers at the head of your document, but you will want to add some insight and some perspective behind your findings. 

Your code itself looks to be arriving at most of the correct answers. So you did much of the heavy lifting of  writing poper code and getting R to function correctly. 

Written Communication **6/10** (I have to be a little hard on you here, there isn't a lot to work with) 
Project Skeleton **9/10** (I looks like you worked through all of the requirements, but your conclusion is a little light) 
Formatting and Display **2/10** (Unless I'm misreading your work, the rubric says **2** for no tables) 
Code Quality **4/10** ("Code executes properly, but is difficult to read." I honestly have a difficult time reading your code.) 
Data Preparation **10/10** 

**31/50**

**Comment by matata668** [comment]
> > Hi @Will-Peters ,
> > Congratulation on your first mini project.
> > Here is my breakdown for grading:
> > Written Communication: 5 The answers are all set up giving us the data for better idea. But, It would be great if we could know what those data meant. You could maybe add the question before the codes and add few sentences as conclusion explaining what those data mean. A couple times, the flow of the project was a bit off. 

> > Project Skeleton: 10

> > Formatting & Display: 7
No tables or code blocks were displayed. Maybe you could use Markdown. This allows you to display your codes in chunk and will make the display easier and in blocks. 

> > Code Quality: 7 There were virtually no comments throughout the code about which block did what. You can use # to write a statement that would explain codes and their function. 

> > Data Preparation: 10 N/A
> > Overall: 39
> 
> Hi, @matata668 ,   My name is Charles, and I’m your TA for this semester. This is a good start. I’m going to encourage you to re-do your peer review for @Will-Peters. Please share additional constructive feedback in each section of your peer review while closely following the [rubric](https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric) for MP01.   Please let me know if you have any questions.
> 
> Thank you!
